USER_CFLAGS = ${CFLAGS} ${X64_CFLAGS} -O0 -D__USER__
USER_LDFLAGS = ${LDFLAGS} -O0 -lgcc

user_deps = $(patsubst %.bin, %.d, ${USER_PROGS})

user_common_sources = entry.c syscall.c
user_common_objects = $(patsubst %.c, ${USER_DIR}/%.o, ${user_common_sources})
user_common_deps = $(patsubst %.o, %.d, ${user_common_objects})

${USER_DIR}/%.bin: ${USER_DIR}/%.o ${user_common_objects} ${STDLIB64}
	$(CC) -T ${USER_DIR}/linker.ld -o $@ $^ ${USER_LDFLAGS}

${USER_DIR}/%.o: ${USER_DIR}/%.c
	$(CC) -c -o $@ $< ${USER_CFLAGS}

-include ${user_deps} ${user_common_deps}
