kernel_lib_sources = memory/map.c \
		     disk/ata.c \
		     console/terminal.c

KERNEL_LIB_BUILDDIR := ${KERNEL_LIB_DIR}/${KERNEL_LIB_ARCH}
kernel_lib_objects := $(patsubst %.c, ${KERNEL_LIB_BUILDDIR}/%.o, ${kernel_lib_sources})

${KERNEL_LIB_BUILDDIR}/${KERNEL_LIB_NAME}: KERNEL_LIB_CFLAGS := ${KERNEL_LIB_CFLAGS}
${KERNEL_LIB_BUILDDIR}/${KERNEL_LIB_NAME}: ${kernel_lib_objects}
	$(AR) cru $@ $^
	$(RANLIB) $@

${KERNEL_LIB_BUILDDIR}/%.o: ${KERNEL_LIB_DIR}/%.c
	@mkdir -p $(@D)
	$(CC) -c -o $@ $^ ${KERNEL_LIB_CFLAGS}
