LOADER_DIR = ${KERNEL_DIR}/loader

LOADER_CFLAGS = ${CFLAGS} ${X86_CFLAGS} \
		-O0 -DKERNEL_BASE=${KERNEL_BASE} -DVADDR_BASE=0
LOADER_LDFLAGS = ${LDFLAGS} -O0 ${X86_LDFLAGS} -lgcc

loader_sources = ${LOADER_DIR}/loader.c
loader_asm_sources = ${LOADER_DIR}/entry.S ${LOADER_DIR}/long_mode.S
loader_objects = $(patsubst %.S, %.o, ${loader_asm_sources}) \
		 $(patsubst %.c, %.o, ${loader_sources})
loader_deps = $(patsubst %.o, %.d, ${loader_objects})

$(LOADER): ${loader_objects} ${KERNEL_LIB32} ${STDLIB32}
	$(CC) -T ${LOADER_DIR}/linker.ld -o $@ $^ ${LOADER_LDFLAGS}

${LOADER_DIR}/%.o: ${LOADER_DIR}/%.S
	$(CC) -c -o $@ $< ${LOADER_CFLAGS}

${LOADER_DIR}/%.o: ${LOADER_DIR}/%.c
	$(CC) -c -o $@ $< ${LOADER_CFLAGS}

-include ${loader_deps}
